# site settings
title: SystemsFair
subtitle: SFU Surrey Tech Career Fair
email: info@systemsfair.ca
description: Software Systems and Mechatronic Systems Engineering Career Fair
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://systemsfair.ca" # the base hostname & protocol for your site
author: Jonathan Wan
street_address: 250-13450 102 Avenue
city: Surrey
state: British Columbia
zip_code: V3T 0A3
country: Canada
phone: (604) 346-9107

# homepage tiles
tiles-source:  pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
